title: Poe Creator Guide
description: Documentation scraped from creator.poe.com/docs
baseurl: "" # Use the repository name as the base URL
url: "https://garethpaul.github.io" # Your GitHub Pages URL

markdown: kramdown
theme: minima
