title: Poe Creator Guide
description: Documentation scraped from creator.poe.com/docs
baseurl: "poe" # leave empty if deploying to the root
url: "https://garethpaul.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minimal
